---
name: Testing

on:
  push:
    branches: [main]
  deployment_status:
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT";
